version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multi-store-sync
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=multi_store_sync
      - DB_USER=postgres
      - DB_PASSWORD=password
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/client/node_modules

  db:
    image: postgres:14
    container_name: multi-store-sync-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=multi_store_sync
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: